insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1000, 'Bilat endosc crush tube', 'Traum rupture of palmar ligament of r rng fngr at MCP/IP jt', 1000);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1001, 'Oth part cholecystectomy', 'Type 1 diab w prolif diab rtnop with trctn dtch macula, bi', 1001);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1002, 'Upper GI series', 'Pressure ulcer of unspecified hip, unstageable', 1002);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1003, 'Eyeball & orbit biopsy', 'Explosion of bicycle tire, subsequent encounter', 1003);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1004, 'Repair colovagin fistula', 'Poisn by unsp nonopi analgs/antipyr/antirheu, asslt, sequela', 1004);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1005, 'Obstetric operation NEC', 'Other dislocation of right shoulder joint, initial encounter', 1005);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1006, 'Remov vag/vulv packing', 'Disrupt of internal operation (surgical) wound, NEC, sequela', 1006);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1007, 'Endosc destruc bronc les', 'Oth current complications following AMI', 1007);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1008, 'Splenic cyst marsupial', 'Pain in unspecified forearm', 1008);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1009, 'Open red-int fix humerus', 'Toxic effect of nitrogen oxides, assault, sequela', 1009);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1010, 'Open reduc-dislocat NEC', 'Unsp injury of intrinsic musc/fasc/tend l thm at wrs/hnd lv', 1010);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1011, 'Periph ganglionect NEC', 'Cervical shortening', 1011);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1012, 'Omt with isoton,isometri', 'Fracture of mandible of oth site, subs for fx w routn heal', 1012);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1013, 'Removal vas ligature', 'Hit by object due to controlled fire, not in bldg', 1013);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1014, 'Pedicle attach to mouth', 'Laceration of blood vessel of right ring finger, subs encntr', 1014);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1015, 'Excision of knee NEC', 'Laceration with foreign body of left ear, subs encntr', 1015);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1016, 'Prostat/sem ves xray NEC', 'Other non-follicular lymphoma, lymph nodes of multiple sites', 1016);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1017, 'Percutan vertebroplasty', 'Acute paralytic poliomyelitis, unspecified', 1017);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1018, 'Inner ear fenestration', 'Shoulder lesion, unspecified, left shoulder', 1018);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1019, 'Detach retina-cryotherap', 'Unspecified injury of right Achilles tendon, init encntr', 1019);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1020, 'Heart countershock NEC', 'Salter-Harris Type III physeal fracture of calcaneus', 1020);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1021, 'Mediastinal tracheostomy', 'Drown in natural water, undetermined intent, init', 1021);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1022, 'Scleral buckle w implant', 'Nondisp transverse fx shaft of l rad, 7thJ', 1022);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1023, 'Dental wiring', 'Oth physl fx low end humer, r arm, subs for fx w delay heal', 1023);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1024, 'Bursectomy of hand', 'Nursemaid''s elbow, left elbow, subsequent encounter', 1024);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1025, 'Cath base invasv ep test', 'Congenital malformation of upper alimentary tract, unsp', 1025);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1026, 'Middle ear excision NEC', 'Oth fx upper end left radius, subs for clos fx w delay heal', 1026);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1027, 'Hand/finger joint biopsy', 'Traum hemor cereb, w LOC of 30 minutes or less, init', 1027);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1028, 'Arthroplasty carpal wit', 'Poisoning by oxytocic drugs, assault, subsequent encounter', 1028);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1029, 'Extracorpor hepat Assis', 'Adverse effect of antidiarrheal drugs, sequela', 1029);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1030, 'Rev knee repl-tibia comp', 'Lacerat flexor musc/fasc/tend unsp finger at forarm lv, init', 1030);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1031, 'Type 5 tympanoplasty', 'Frostbite with tissue necrosis of unspecified ankle, sequela', 1031);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1032, 'Other post segment ops', 'Poisoning by smallpox vaccines, accidental, subs', 1032);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1033, 'Alcohol rehab/detox', 'Incomplete atypical femoral fracture, unspecified leg', 1033);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1034, 'Body measurement', 'Other streptococcal arthritis, unspecified knee', 1034);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1035, 'Replace prolapsed cord', 'Unspecified intracapsular fracture of right femur, sequela', 1035);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1036, 'Partial shoulder replace', 'Malignant neoplasm of middle ear', 1036);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1037, 'Contrast laryngogram', 'Poisoning by emetics, undetermined, sequela', 1037);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1038, 'Vena cav angiocardiogram', 'Oth disp fx of second cervical vertebra, init for opn fx', 1038);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1039, 'Cl fx reduc-finger', 'Toxic effect of coral snake venom, self-harm, subs', 1039);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1040, 'Open fx reduction NEC', 'Fall on board (nonpowered) inflatable craft, init encntr', 1040);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1041, 'Periph nerve inject NEC', 'Other specified disorders of cornea, bilateral', 1041);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1042, 'Ureteral anastomosis NEC', 'Idiopathic aseptic necrosis of humerus', 1042);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1043, 'Bone graft to femur', 'Adult pulmonary Langerhans cell histiocytosis', 1043);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1044, 'Micro exam NEC', 'Other chorioretinal scars, unspecified eye', 1044);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1045, 'Periren/vesicle op NEC', 'Unspecified open wound of left upper arm, initial encounter', 1045);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1046, 'Closed tricusp valvotomy', 'Disorders of autonomic nervous system', 1046);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1047, 'Bronch/lung dx proc NEC', 'Pathological fracture, left humerus, sequela', 1047);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1048, 'Portal contr phlebogram', 'Partial traumatic amputation of unsp foot at ankle level', 1048);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1049, 'Sm bowel-rect stump anas', 'Malignant neoplasm of palate, unspecified', 1049);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1050, 'Closed thyroid gland bx', 'Disp fx of coronoid pro of l ulna, 7thM', 1050);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1051, 'App ext fix dev-monoplan', 'Congenital malformation of great arteries, unspecified', 1051);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1052, 'Portal contr phlebogram', 'Retained (old) magnetic fb in ant chamber, unsp eye', 1052);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1053, 'Lumbosac spine x-ray NEC', 'Adverse effect of local antifung/infect/inflamm drugs, init', 1053);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1054, 'Subtalar fusion', 'Oth spon disruption of medial collat ligament of right knee', 1054);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1055, 'Limb lengthen-tib/fibula', 'Nondisp fx of acromial process, unsp shoulder, init', 1055);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1056, 'Opn pull-thru res rectum', 'Familial chondrocalcinosis, ankle and foot', 1056);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1057, 'Cholecystotomy NEC', 'Motorcycle rider injured in collision with pedal cycle', 1057);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1058, 'Tot ostect-metatars/tars', 'Adverse effect of anticholinesterase agents, subs encntr', 1058);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1059, 'Cleft palate correction', 'Paralytic lagophthalmos left eye, unspecified eyelid', 1059);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1060, 'Adenoidectomy', 'Unsp fx upr end r tibia, 7thJ', 1060);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1061, 'Sm bowel-rect stump anas', 'Unspecified open wound of unspecified ear, initial encounter', 1061);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1062, 'Remov ext immobilization', 'Acute embolism and thrombosis of deep vein of l low extrem', 1062);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1063, 'Insert gastric tube NEC', 'Complete loss of teeth, unspecified cause', 1063);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1064, 'Remov vas deferens valve', 'Burn of third degree of chin, sequela', 1064);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1065, 'Suture entropion repair', 'Occup of special agri vehicle injured nontraf, sequela', 1065);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1066, 'Endarterectomy NOS', 'Displaced fracture of body of hamate bone, left wrist', 1066);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1067, 'Hemodialysis', 'Subluxation of metatarsophalangeal joint of unsp toe(s)', 1067);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1068, 'Suture kidney laceration', 'Superficial foreign body of unsp part of head, init encntr', 1068);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1069, 'Scleral buckling NEC', 'Laceration with foreign body of toe with damage to nail', 1069);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1070, 'Dilat enterostomy stoma', 'Sltr-haris Type IV physl fx upr end rad, unsp arm, 7thD', 1070);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1071, 'Other destru pancrea les', 'Sltr-haris Type II physl fx upr end humer, r arm, 7thK', 1071);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1072, 'Suture peptic ulcer NOS', 'Occ of anml-drn vehicle injured in clsn w stcar, sequela', 1072);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1073, 'Open reduc-dislocat NOS', 'Lacerat musc/fasc/tend long hd bicep, left arm, sequela', 1073);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1074, 'Alcohol rehab/detox', 'Unspecified choroidal hemorrhage, bilateral', 1074);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1075, 'Metatarsophalangeal fus', 'Path fx in neopltc dis, unsp shldr, subs for fx w routn heal', 1075);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1076, 'Perf keratopl w autogrft', 'Pers hx of unintended awareness under general anesthesia', 1076);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1077, 'Excis metacar/car-graft', 'Person outsd bus inj pick-up truck, pk-up/van nontraf, subs', 1077);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1078, 'Cervical fistula repair', 'Unsp open wound of unsp lesser toe(s) w damage to nail, subs', 1078);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1079, 'Enterovesico fist repair', 'Benign neoplasm of meninges, unspecified', 1079);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1080, 'Total wrist replacement', 'Oth soft tissue disord related to use/pressure, r shoulder', 1080);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1081, 'Instrument delivery NOS', 'Nondisp fx of hook process of hamate bone, r wrist, sequela', 1081);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1082, 'Type 2 tympanoplasty', 'Helicobacter pylori as the cause of diseases classd elswhr', 1082);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1083, 'Lower lid rhytidectomy', 'Corrosion of third degree of trunk, unsp site, init encntr', 1083);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1084, 'Oth chest cage rep/plast', 'Oligohydramnios, third trimester, fetus 4', 1084);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1085, 'Ventr septa def rep NEC', 'Unspecified nystagmus', 1085);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1086, 'Periurethral incision', 'Type 1 diabetes w unsp diabetic retinopathy w macular edema', 1086);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1087, 'Imp limb length kinetic', 'Sltr-haris Type IV physl fx lower end of unsp femur, sequela', 1087);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1088, 'Bact smear NOS', 'Sltr-haris Type II physeal fx lower end of left tibia', 1088);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1089, 'Open mediastinal biopsy', 'Anterior subluxation of right radial head, subs encntr', 1089);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1090, 'Ocular prosthetics', 'Post-void dribbling', 1090);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1091, 'Max art lig for epistax', 'Subluxation of proximal interphaln joint of r idx fngr, subs', 1091);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1092, 'Leg vein resect/anastom', 'Unspecified injury of lung, unilateral, subsequent encounter', 1092);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1093, 'Thymectomy NOS', 'Fb in oth and multiple parts of external eye, r eye, subs', 1093);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1094, 'Rectorectostomy', 'Prolonged second stage (of labor)', 1094);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1095, 'Replace gastrostomy tube', 'Spontaneous rupture of extensor tendons, right forearm', 1095);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1096, 'Shoulder arthroplast NEC', 'Pathological fracture, left tibia, subs for fx w delay heal', 1096);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1097, 'Ophthalmoscopy', 'Oth stimulant abuse w stimulant-induced sexual dysfunction', 1097);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1098, 'Closure of tracheostomy', 'Posterior scleritis, bilateral', 1098);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1099, 'Osteoclasis-metatar/tar', 'Maternal care for other malpresentation of fetus, fetus 2', 1099);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1100, 'Ureteropexy', 'Partial traumatic transphalangeal amputation of unsp thumb', 1100);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1101, 'Splenotomy', 'Pasngr on bus injured in clsn w rail trn/veh in traf, subs', 1101);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1102, 'Lg-to-lg bowel anastom', 'Inj unsp blood vess at hip and thi lev, right leg, sequela', 1102);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1103, 'Intracarot amobarb test', 'Displaced fracture of medial condyle of unspecified femur', 1103);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1104, 'Bronchial ligation', 'Insect bite (nonvenomous) of right shoulder, sequela', 1104);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1105, 'Radial keratotomy', 'Cerebral infarction due to thrombosis of left cereblr artery', 1105);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1106, 'Open reduc-int fix femur', 'Chorioamnionitis, first trimester, fetus 4', 1106);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1107, 'Perianal incision NEC', 'Poisoning by oth vaccines and biolg substances, undet, subs', 1107);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1108, 'Egd with closed biopsy', 'Unsp inj unsp musc/fasc/tend at shldr/up arm, r arm, init', 1108);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1109, 'Cnt intraart bld gas mon', 'Nondisp oblique fx shaft of l tibia, 7thE', 1109);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1110, 'Spinal x-ray NEC', 'Pathological fracture, unsp femur, subs for fx w malunion', 1110);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1111, 'Remov post segmnt FB NOS', 'Unspecified place or not applicable', 1111);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1112, 'Tibia/fibula sequestrec', 'Acute and chronic respiratory failure with hypoxia', 1112);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1113, 'Bilateral vulvectomy', 'Lac w fb of unsp lesser toe(s) w/o damage to nail, sequela', 1113);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1114, 'Endomet synechiae divis', 'Injury of deep peroneal nerve at ank/ft level, left leg', 1114);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1115, 'Sclera reinforcement NEC', 'Displacement of heart valve prosthesis, initial encounter', 1115);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1116, 'Micro exam-endocrine NEC', 'Superficial foreign body of throat, sequela', 1116);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1117, 'Insert pseudophakos NOS', 'Burn of 2nd deg mul sites of left wrist and hand, subs', 1117);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1118, 'Abdominal wall incision', 'Traum hemor left cerebrum w LOC of 30 minutes or less', 1118);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1119, 'BBBD via infusion', 'Sprain of other ligament of ankle', 1119);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1120, 'Thorac esophagogastrost', 'Toxic effect of insecticides, accidental, init', 1120);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1121, 'Injct/infus glucarpidase', 'Neoplasm of uncertain behavior of kidney', 1121);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1122, 'Incision of lid margin', 'Nondisp fx of epiphy (separation) (upper) of l femr, 7thH', 1122);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1123, 'Spinal x-ray NEC', 'Problems related to social environment', 1123);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1124, 'Proctosigmoidosc thru st', 'Unsp dislocation of unspecified acromioclavicular joint', 1124);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1125, 'C-vasc scan/isotop funct', 'Unsp inj musc/tend peroneal grp at low leg lev, r leg, subs', 1125);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1126, 'Femoral division NEC', 'Injury of other nerves at forearm level', 1126);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1127, 'Secondary insert lens', 'Type 3 fracture of sacrum', 1127);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1128, 'Percut tunica aspiration', 'Displ commnt fx shaft of rad, l arm, 7thH', 1128);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1129, 'Intelligence test admin', 'Other rupture of muscle (nontraumatic), unspecified site', 1129);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1130, 'Tot ostect-metatars/tars', 'Unsp fx shaft of r ulna, 7thE', 1130);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1131, 'Elevate skull fx fragmnt', 'Nondisp artic fx head of r femr, 7thG', 1131);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1132, 'Barium swallow', 'Burn due to canoe or kayak on fire', 1132);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1133, 'Manl reduct stoma prolap', 'Arthropathy following intestinal bypass, right ank/ft', 1133);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1134, 'Bronchoscopy thru stoma', 'Person outside car injured in clsn w statnry object in traf', 1134);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1135, 'Dilat frontonasal duct', 'Nondisp fx of epiphy (separation) (upper) of unsp femr, init', 1135);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1136, 'Repair of intestine NEC', 'Neoplasm of uncertain behavior of larynx', 1136);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1137, 'Bilat tubal division NEC', 'Adult T-cell lymph/leuk (HTLV-1-assoc) not achieve remission', 1137);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1138, 'Lacrim sac/passage excis', 'Other physeal arrest of forearm', 1138);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1139, 'C & s-nervous syst', 'Otorrhea', 1139);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1140, 'Other repair of knee', 'Chalcosis, bilateral', 1140);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1141, 'Cardiac rhythm conv NEC', 'Oth fx shaft of left ulna, subs for clos fx w malunion', 1141);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1142, 'Remov ureteral drain', 'Alcoholic cirrhosis of liver', 1142);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1143, 'Other skull dx procedure', 'Anterior subluxation of proximal end of tibia, right knee', 1143);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1144, 'Ovarian dx procedure NEC', 'Displaced bicondylar fracture of right tibia, sequela', 1144);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1145, 'Anal anastomosis', 'Other anterior dislocation of right hip, subs encntr', 1145);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1146, 'Intraop cor flr vas angi', 'Abrasion of lower back and pelvis, subsequent encounter', 1146);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1147, 'Remov abdomen device NEC', 'Colles'' fx unsp rad, subs for opn fx type I/2 w delay heal', 1147);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1148, 'Other skin & subq i & d', 'Mature B-cell leukemia Burkitt-type, in relapse', 1148);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1149, 'Femoral sequestrectomy', 'Other and unspecified arthropathy', 1149);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1150, 'Remov mechanical kidney', 'Lacerat intrns musc/fasc/tend r rng fngr at wrs/hnd lv, sqla', 1150);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1151, 'Grp therap psychsex dysf', 'Laceration of unspecified renal artery, subsequent encounter', 1151);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1152, 'Tendon sheath explorat', 'Other amyloidosis', 1152);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1153, 'Heart aneurysm excision', 'Unsp car occupant injured in clsn w rail trn/veh in traf', 1153);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1154, 'Skin excision for graft', 'Nondisp fx of cuboid bone of r ft, subs for fx w delay heal', 1154);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1155, 'Creat esophagastr sphinc', 'Arthropathies in oth diseases classified elsewhere, shoulder', 1155);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1156, 'Pacemaker volt threshold', 'Drown due to fall/jump fr oth burning unpowered watercraft', 1156);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1157, 'Lap reimplant of ovary', 'Laceration of brachial artery, right side, initial encounter', 1157);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1158, 'Dyslexia training', 'Oth parlyt syndrome fol unsp cerebvasc disease aff unsp side', 1158);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1159, 'Digital rectal exam', 'Underdosing of nonopioid analges/antipyret, NEC, init', 1159);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1160, 'Cl fx reduc-radius/ulna', 'Unsp disp fx of surg nk of r humer, subs for fx w routn heal', 1160);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1161, 'Suture peptic ulcer NOS', 'Burn due to sailboat on fire, initial encounter', 1161);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1162, 'Autoimmune dis immunizat', 'Path fx in neopltc disease, r ulna, subs for fx w malunion', 1162);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1163, 'Inject tendon of hand', 'Dislocation of L4/L5 lumbar vertebra, initial encounter', 1163);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1164, 'Saliv glnd dx proc NEC', 'Acquired deformity of pinna, unspecified ear', 1164);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1165, 'Patellar biopsy', 'Corrosion of unspecified degree of right ear, subs encntr', 1165);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1166, 'Tot exc pituit-transfron', 'Unsp war operations occurring after, milt, sequela', 1166);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1167, 'Toxicology-ent/larynx', 'Traum rupture of palmar ligament of r idx fngr at MCP/IP jt', 1167);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1168, 'Percu endosc jejunostomy', 'Prsn brd/alit a 3-whl mv injured in clsn w ped/anml, sequela', 1168);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1169, 'Color vision study', 'Poisoning by 4-Aminophenol derivatives, undetermined', 1169);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1170, 'Free skin graft NEC', 'Toxic eff of halgn deriv of aromatic hydrocrb, slf-hrm, subs', 1170);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1171, 'Wedge osteotomy NOS', 'Crushing injury of right knee, subsequent encounter', 1171);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1172, 'Dermal regener graft', 'Salter-Harris Type I physeal fracture of upper end of femur', 1172);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1173, 'Local lg bowel perfusion', 'Other specified osteochondrodysplasias', 1173);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1174, 'Revis enuc socket w grft', 'Displ seg fx shaft of ulna, l arm, 7thE', 1174);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1175, 'Inject/infuse NEC', 'Personal history of malignant neoplasm of urinary tract', 1175);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1176, '1 extraoc muscl resect', 'Poisoning by oth antipsychot/neurolept, accidental, init', 1176);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1177, 'Disarticulation of wrist', 'Other subluxation of unspecified knee, subsequent encounter', 1177);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1178, 'Esophagoscopy by incis', 'Oth postproc complications and disorders of resp sys, NEC', 1178);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1179, 'Penile biopsy', 'Alopecia areata, unspecified', 1179);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1180, 'Peritoneal repair NEC', 'Poisoning by aminoglycosides, undetermined, sequela', 1180);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1181, 'Mastopexy', 'Antepartum hemorrhage, unspecified, third trimester', 1181);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1182, 'Botulism antitoxin admin', 'Disp fx of anterior wall of unspecified acetabulum, sequela', 1182);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1183, 'Hand synovectomy', 'Pain due to other internal prosth dev/grft, subs', 1183);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1184, 'Replantation of scalp', 'Nondisp spiral fx shaft of ulna, l arm, 7thR', 1184);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1185, 'Repair eyeball rupture', 'Displ suprcndl fx w/o intrcndl extn low end l femr, 7thK', 1185);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1186, 'Nasal sinus fistula clos', 'Squamous cell carcinoma of overlapping sites of skin', 1186);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1187, 'Audit & vestib test NEC', 'Other effects of air pressure and water pressure, sequela', 1187);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1188, 'Remove imp device NOS', 'Unsp fracture of second metacarpal bone, right hand, init', 1188);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1189, 'Scarification of pleura', 'Unspecified open wound of left breast, sequela', 1189);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1190, '1 int mam-cor art bypass', 'Pasngr in pk-up/van injured in clsn w ped/anml in traf, init', 1190);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1191, 'Functional pt evaluation', 'Nontraumatic subarachnoid hemorrhage from oth intracran art', 1191);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1192, 'Other muscle/fasc suture', 'Superficial foreign body, right lower leg, subs encntr', 1192);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1193, 'Dx ultrasound-grav uter', 'Other contact with dolphin, subsequent encounter', 1193);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1194, 'Common cold vaccination', 'Strain of muscle and tendon of unsp wall of thorax, init', 1194);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1195, 'Gb-to-hepat duct anast', 'Unsp open wound of right cheek and TMJ area, sequela', 1195);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1196, 'Local renal perfusion', 'Hyperimmunoglobulin E [IgE] syndrome', 1196);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1197, 'Up limb sft tis xray NEC', 'Unsp focal TBI w loss of consciousness of 1-5 hrs 59 min', 1197);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1198, 'Ovarian wedge resection', 'Burn of unspecified degree of left axilla', 1198);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1199, 'Proximal pancreatectomy', 'Laceration w fb of unsp lesser toe(s) w damage to nail, subs', 1199);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1200, 'Rvrs totl shldr replacmt', 'Disp fx of l tibial tuberosity, 7thM', 1200);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1201, 'Oth plastic repair palat', 'Diseases of vocal cords and larynx, not elsewhere classified', 1201);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1202, 'Micro exam-lymph sys NEC', 'Keratopathy (bullous aphakic) fol cataract surgery, unsp eye', 1202);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1203, 'Distal gastrectomy', 'Foliclar lymph grade IIIa, nodes of ing rgn and lower limb', 1203);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1204, 'Breast injection', 'Burn of second degree of left thumb (nail)', 1204);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1205, 'Int insert 1-cham, non', 'Post-traumatic urethral stricture, female', 1205);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1206, 'Tot face bone ostect NEC', 'Pasngr in pk-up/van injured in nonclsn trnsp acc nontraf', 1206);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1207, 'Debrid opn fx-toe', 'Nondisp fx of body of scapula, r shldr, 7thG', 1207);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1208, 'Inject/infuse NEC', 'Lacerat blood vessels at lower leg level, left leg, sequela', 1208);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1209, 'Omt with hi-vel,lo-ampli', 'Alcohol dependence with withdrawal, uncomplicated', 1209);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1210, 'Ins strn fix w rgd plate', 'Peroneal tendinitis', 1210);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1211, 'Uterine art emb w/o coil', 'Intcran inj w loss of consciousness >24 hr w ret consc lev', 1211);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1212, 'Freeing of vessel', 'Newborn light for gestational age, 2000-2499 grams', 1212);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1213, 'Esophageal graft NEC', 'Liver & biliary trac disord in preg, chldbrth and the puerp', 1213);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1214, 'Other neuroplasty', 'Accidental twist by another person, initial encounter', 1214);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1215, 'Conduit rt vent-pul art', 'Low-tension glaucoma, right eye, severe stage', 1215);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1216, 'Bil fem hern repair-grft', 'Chronic respiratory failure, unsp w hypoxia or hypercapnia', 1216);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1217, 'Skull & brain op NEC', 'Spondylolisthesis, thoracic region', 1217);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1218, 'Excision of anus', 'Crushing injury of unspecified hip with thigh, subs encntr', 1218);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1219, 'Rev hip repl-acetab comp', 'Other specified urinary incontinence', 1219);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1220, 'Dx ultrasound NEC', 'Alcohol use, unsp w alcoh-induce persist amnestic disorder', 1220);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1221, 'Rad dissec periaort node', 'Blister (nonthermal), left lower leg, subsequent encounter', 1221);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1222, 'Stereo radiosurgery NEC', 'Adverse effect of iminostilbenes', 1222);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1223, 'Upper lid rhytidectomy', 'Adhes due to fb acc left in body following heart cath, init', 1223);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1224, 'Trabeculectom ab externo', 'Ped w convey injured pick-up truck, pk-up/van in traf, subs', 1224);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1225, 'Renal operation NEC', 'Other physeal fracture of upper end of tibia', 1225);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1226, 'Quadricepsplasty', 'Underdosing of methadone, initial encounter', 1226);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1227, 'Arthroscopy NOS', 'Disp fx of coronoid pro of l ulna, 7thJ', 1227);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1228, 'Oth lap loc exc dest ova', 'Insect bite (nonvenomous), left ankle, initial encounter', 1228);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1229, 'Toxicology-eye', 'Rheumatoid bursitis, unspecified elbow', 1229);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1230, 'Iridoplasty NEC', 'Stress fracture, right toe(s), init encntr for fracture', 1230);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1231, 'Rectal packing', 'Underdosing of tetracyclic antidepressants, subs encntr', 1231);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1232, 'Close thoracic duct fist', 'Oth intraop and postproc comp and disord of ear/mastd, NEC', 1232);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1233, 'Tibia/fibul wedg osteot', 'Puncture wound without foreign body, unspecified foot', 1233);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1234, 'GI tract instillat NEC', 'Adverse effect of sulfonamides', 1234);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1235, 'Exploratory thoracotomy', 'Osteopathy after poliomyelitis, other site', 1235);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1236, 'Electron teleradiotherap', 'Unsp inj extn musc/fasc/tend l idx fngr at forarm lv, subs', 1236);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1237, 'Perineal urethroscopy', 'Contusion of left ankle', 1237);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1238, 'Cont inv mec ven <96 hrs', 'Fall same lev from slip/trip w strk agnst sharp glass, sqla', 1238);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1239, 'Closed spleen biopsy', 'Unspecified physeal fracture of right calcaneus, 7thK', 1239);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1240, 'Renal injection NEC', 'Traum hemor left cerebrum w LOC of 31-59 min, init', 1240);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1241, 'Excision hand joint NEC', 'Sprain of interphalangeal joint of left lesser toe(s), subs', 1241);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1242, 'Labial frenumectomy', 'Profound intellectual disabilities', 1242);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1243, 'Urethral pressure profil', 'Mild intermittent asthma', 1243);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1244, 'Remov ant segmnt FB NOS', 'Nondisp trimalleol fx r low leg, 7thN', 1244);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1245, 'Destruc-ankle lesion NEC', 'Person outsd 3-whl mv inj in clsn w 2/3-whl mv nontraf, subs', 1245);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1246, 'Metatar/tar division NEC', 'Burn of third degree of upper back, sequela', 1246);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1247, 'Cardiopulm resuscita NOS', 'Corrosion of unspecified degree of left axilla', 1247);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1248, 'Partial humerectomy NEC', 'Psychological abuse complicating pregnancy, unsp trimester', 1248);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1249, 'Exploratory laparotomy', 'Military operations involving other explosions and fragments', 1249);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1250, 'Anal biopsy', 'Unsp traum nondisp spondylolysis of fifth cervcal vert, init', 1250);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1251, 'Adrenal incision', 'Fracture of alveolus of mandible, unspecified side, 7thB', 1251);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1252, 'Biopsy of diaphragm', 'Lac w fb of l frnt wl of thorax w/o penet thor cavity, sqla', 1252);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1253, 'Ant synechia lysis NEC', 'Chronic or unsp gastrojejunal ulcer w both hemor and perf', 1253);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1254, 'Nephrost/pyelost irrigat', 'Poisoning by succinimides and oxazolidinediones, undet, subs', 1254);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1255, 'Pedicle attach to mouth', 'Chronic hepatic failure', 1255);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1256, 'Fat graft to breast', 'Other superficial bite of left foot', 1256);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1257, 'Facial bone x-ray NEC', 'Disp fx (avulsion) of medial epicondyle of r humerus, init', 1257);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1258, 'Percutan hrt assist syst', 'Breakdown of intrauterine contracep dev, sequela', 1258);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1259, 'Remove ureteral stimulat', 'Oth nondisp fx of lower end r humer, subs for fx w nonunion', 1259);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1260, 'Oth conjunc destruc proc', 'Unsp fracture of right ilium, init for clos fx', 1260);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1261, 'Blepharorrhaphy severing', 'Chronic salpingitis', 1261);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1262, 'Pull-thru rect resec NEC', 'Injury of ulnar nerve at wrist and hand level of unsp arm', 1262);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1263, 'Electroencephalogram', 'Lead-induced chronic gout, hand', 1263);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1264, 'Other suprapu cystostomy', 'Lgl intervnt w inj by rifl pelet, law enforc offl inj, subs', 1264);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1265, 'Fetal ops-facilitate del', 'Posterior displaced fracture of sternal end of left clavicle', 1265);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1266, 'Cervical cyst marsupial', 'Posterior disloc of proximal end of tibia, left knee, init', 1266);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1267, 'Peripheral nerve ops NEC', 'Path fx in oth disease, l shoulder, subs for fx w malunion', 1267);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1268, 'Exc maj les lid ful-thic', 'Inj unsp blood vessel at ank/ft level, left leg, init', 1268);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1269, 'Reduce renal pedicl tors', 'Central dislocation of left hip', 1269);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1270, 'Brain repair', 'Influenza due to unidentified influenza virus', 1270);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1271, 'Suture of pharyngeal lac', 'Poisoning by salicylates, assault', 1271);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1272, 'Other skeletal x-ray', 'Nondisp fx of coracoid process, unsp shoulder, sequela', 1272);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1273, 'Other perm tracheostomy', 'Pnctr w fb of abd wall, epigst rgn w penet perit cav, sqla', 1273);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1274, 'C & s-musculoskeletal', 'Displ seg fx shaft of rad, unsp arm, 7thH', 1274);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1275, 'Tot rep truncus arterios', 'Struck by turtle, subsequent encounter', 1275);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1276, 'Lo limb sft tis xray NEC', 'Lacerat great saphenous at lower leg level, right leg, subs', 1276);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1277, 'After-catar discission', 'Unspecified physeal fracture of right calcaneus, 7thP', 1277);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1278, 'Inject implant urethra', 'Listerial sepsis', 1278);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1279, 'Insert othr spin device', 'GM2 gangliosidosis', 1279);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1280, 'Exc pituit les-transphen', 'Displ transverse fx shaft of r ulna, 7thE', 1280);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1281, 'Ureteroneocystostomy', 'Unsp fx right patella, subs for clos fx w routn heal', 1281);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1282, 'Destruc-elbow lesion NEC', 'Partial traumatic amputation of right midfoot, sequela', 1282);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1283, 'Anal anastomosis', 'Prsn brd/alit pk-up/van injured in collision w hv veh', 1283);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1284, 'Arthrodesis NEC', 'Dislocation of right ankle joint, initial encounter', 1284);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1285, 'Psychodrama', 'Subluxation of T6/T7 thoracic vertebra, sequela', 1285);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1286, 'Remov pyelos/nephros tub', 'Other contact with macaw, subsequent encounter', 1286);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1287, 'Pros rep endocar cushion', 'Burkitt lymphoma', 1287);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1288, 'Electromyogram of eye', 'Sltr-haris Type III physeal fx lower end of left tibia, init', 1288);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1289, 'Distal pancreatectomy', 'Unsp fx shaft of r radius, subs for clos fx w nonunion', 1289);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1290, 'Open chest trans revasc', 'Toxic effect of unsp seafood, accidental (unintentional)', 1290);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1291, 'Rep scler staphyloma NEC', 'Other specified injuries of thorax', 1291);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1292, 'Peritoneal incision', 'Female genital tract-skin fistulae', 1292);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1293, 'Pedicle graft advancemen', 'Chronic or unspecified duodenal ulcer with perforation', 1293);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1294, 'Other arthrotomy NOS', 'Nondisp fx of base of 3rd MC bone, r hand, 7thP', 1294);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1295, 'Impl fallop tube prosth', 'Ped on sktbrd injured in collision w hv veh, unsp, sequela', 1295);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1296, 'Ultrasound study of eye', 'Sprain of interphalangeal joint of other finger, sequela', 1296);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1297, 'Crisis intervention', 'Osteomyelitis of vertebra, sacral and sacrococcygeal region', 1297);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1298, 'Exc chest cage bone les', 'Unspecified open wound, unspecified foot, sequela', 1298);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1299, 'Skull x-ray NEC', 'Other specified injuries of right hip, sequela', 1299);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1300, 'Dental scaling & debride', 'Other contact with turtle, sequela', 1300);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1301, 'Remove solitary testis', 'Other and unsp malignant neoplasm of skin, unspecified', 1301);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1302, 'Periph nerve transposit', 'Disp fx of distal phalanx of unspecified finger, sequela', 1302);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1303, 'Knee arthroscopy', 'Displaced fracture of lunate [semilunar], right wrist', 1303);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1304, 'Ins/repl interspine dev', 'Maternal care for disproportion due to unusually large fetus', 1304);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1305, 'Interruption vena cava', 'Streptococcal meningitis', 1305);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1306, 'Alcoholism counselling', 'Enophthalmos due to atrophy of orbital tissue', 1306);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1307, 'Head/neck ves incis NEC', 'Fall from, out of or through window, initial encounter', 1307);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1308, 'Family therapy', 'Fall d/t clsn betw oth pwr wtrcrft and oth wtrcrft/obj, init', 1308);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1309, 'Intra-abd lg bowel manip', 'Fx superior rim of unsp pubis, subs for fx w nonunion', 1309);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1310, 'Behavior therapy', 'Type 1 diabetes mellitus with hyperglycemia', 1310);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1311, 'Remov thor ther dev NEC', 'Adjustment insomnia', 1311);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1312, 'Other bone division NOS', 'Barton''s fx unsp rad, subs for opn fx type 3A/B/C w nonunion', 1312);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1313, 'Tracheostomy toilette', 'Diffuse secondary atrophy of choroid', 1313);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1314, 'Leg vein resect w replac', 'Flat anterior chamber hypotony of eye', 1314);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1315, 'Remov epithel downgrowth', 'Nondisp transverse fx shaft of r ulna, 7thD', 1315);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1316, 'Diagnostic imaging NOS', 'Rosacea', 1316);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1317, 'Other vaginal dilation', 'Major laceration of femoral artery, left leg, sequela', 1317);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1318, 'Ex chest cage bone-gft', 'Osteochondropathy, unspecified, right hand', 1318);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1319, 'Mri musculoskeletal', 'Injury of radial nerve at wrist and hand level', 1319);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1320, 'Robotic ast proc NEC/NOS', 'Nondisp fx of med condyle of r femr, 7thE', 1320);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1321, 'Cl fx reduc-tibia/fibula', 'Laceration of dorsal artery of right foot, sequela', 1321);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1322, 'Synovectomy-site NEC', 'Crushing injury of left lesser toe(s), subsequent encounter', 1322);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1323, 'Endosc destruc esoph les', 'Other neonatal aspiration', 1323);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1324, 'Heterograft to skin', 'Nondisp fx of body of scapula, unsp shldr, 7thD', 1324);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1325, 'Removal of FB NOS', 'I/I react d/t indwelling ureteral stent, subs', 1325);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1326, 'Applic ext fix dev NOS', 'Disp fx of r tibial tuberosity, 7thF', 1326);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1327, 'Hip synovectomy', 'Oth cause of accidental non-transport drown, init', 1327);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1328, 'App ext fix dev-monoplan', 'Poisoning by oth estrogens and progestogens, self-harm, subs', 1328);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1329, 'Stapes mobilization', 'Cocaine dependence w intoxication w perceptual disturbance', 1329);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1330, 'Kidney transplant NEC', 'Unsp inj flexor musc/fasc/tend at forarm lv, unsp arm, sqla', 1330);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1331, 'Percu nephrostm w/o frag', 'Inj flexor musc/fasc/tend r idx fngr at wrs/hnd lv, subs', 1331);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1332, 'Orbitotomy NEC', 'Superficial frostbite of left arm, sequela', 1332);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1333, 'Percutan renal aspirat', 'Appendicular concretions', 1333);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1334, 'Thoracentesis', 'Alcoholic hepatic failure without coma', 1334);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1335, 'Bowel diagnost proc NEC', 'Complete loss of teeth due to trauma, class I', 1335);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1336, 'Auto bone mt w/o purg', 'Displ seg fx shaft of ulna, r arm, 7thF', 1336);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1337, 'Total body perfusion', 'Occupant of stcar injured in collisn/hit by roll stok, init', 1337);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1338, 'Other tracheal operation', 'Path fx in neopltc dis, r radius, subs for fx w routn heal', 1338);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1339, 'Other gastrostomy', 'Other testicular dysfunction', 1339);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1340, 'Manl reduct stoma prolap', 'Displaced fracture of posterior process of unspecified talus', 1340);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1341, 'Lid marg lac rx-part th', 'Corrosion of eye and adnexa, part unspecified', 1341);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1342, 'Total body scan', 'Lateral disloc of proximal end of tibia, left knee, sequela', 1342);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1343, 'Instrument delivery NOS', 'Oth psychoactive substance abuse w psychotic disorder', 1343);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1344, 'Disarticulation of hip', 'Poisoning by anthelminthics, intentional self-harm, sequela', 1344);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1345, 'Dorsal/lat slit prepuce', 'Minor laceration of left external jugular vein, subs encntr', 1345);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1346, 'Intracardiac echocardio', 'Path fx in neopltc dis, oth site, subs for fx w delay heal', 1346);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1347, 'Excis lesion of muscle', 'Bent bone of l rad, subs for opn fx type 3A/B/C w malunion', 1347);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1348, 'Ins or rep cement spacer', 'Unsp fracture of r low leg, init for opn fx type 3A/B/C', 1348);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1349, 'Insrt non-impl circ dev', 'Barton''s fx r rad, subs for opn fx type 3A/B/C w routn heal', 1349);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1350, 'Iridotomy w transfixion', 'Squamous cell carcinoma skin/ ear and external auric canal', 1350);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1351, 'Lid reconst w skin graft', 'Nondisp comminuted fx shaft of radius, unsp arm, sequela', 1351);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1352, 'Arbovirus vaccinat NEC', 'Toxic eff of carb monx from incmpl combst dmst fuel, asslt', 1352);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1353, 'Unilat ing hern rep NOS', 'Unspecified open wound, unspecified ankle', 1353);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1354, 'Open mediastinal biopsy', 'Laceration with foreign body of unsp wrist, init encntr', 1354);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1355, 'Abdominal vein excision', 'Poisoning by dental drugs, topically applied, undet, init', 1355);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1356, 'Tot rep truncus arterios', 'Displ seg fx shaft of l tibia, 7thM', 1356);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1357, 'Loc exc les tibia/fibula', 'Driver of 3-whl mv inj in clsn w nonmtr veh nontraf, subs', 1357);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1358, 'Excise minor les lid NEC', 'Basal cell carcinoma of skin of eyelid, including canthus', 1358);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1359, 'Splenotomy', 'Other specified diseases of pericardium', 1359);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1360, 'Mech vitrectomy NEC', 'Unspecified blood donor', 1360);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1361, 'Ligation of vas deferens', 'Laceration of right Achilles tendon', 1361);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1362, 'Plastic rep ext ear NEC', 'Polyneuropathy, unspecified', 1362);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1363, 'Scleral operation NEC', 'Displ transverse fx shaft of l fibula, 7thF', 1363);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1364, 'Other myectomy of hand', 'Unsp inj unsp musc/fasc/tend at forarm lv, right arm, subs', 1364);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1365, 'Local destr ova les NEC', 'Unsp fracture of shaft of unsp tibia, init for clos fx', 1365);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1366, 'Soft tissue aspirat NEC', 'Sequelae of leprosy', 1366);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1367, 'Remov intrauterine pack', 'Asslt by push/place victim in front of moving object, sqla', 1367);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1368, 'Cl fx reduc-metatar/tar', 'Oth injury of blood vessel of unspecified thumb, sequela', 1368);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1369, 'Typhoid/paratyphoid vacc', 'Burn 2nd deg mul sites of right lower limb, ex ank/ft, sqla', 1369);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1370, 'Subtotl abd hyst NEC/NOS', 'Crushed betw sailboat and oth wtrcrft/obj due to collision', 1370);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1371, 'Abd wall suture NEC', 'Other fracture of lower end of unspecified femur, sequela', 1371);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1372, 'Vesic fistula repair NEC', 'Unsp inj unsp blood vess at lower leg level, left leg, init', 1372);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1373, 'Total body perfusion', 'Athscl autologous artery CABG w oth angina pectoris', 1373);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1374, 'Adrenal reimplantation', 'Obst labor due to incmpl rotation of fetal head, fetus 1', 1374);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1375, 'Esophageal dx proc NEC', 'Pnctr w/o fb of left great toe w/o damage to nail, sequela', 1375);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1376, 'Intestinal biopsy NOS', 'Leakage of intraperitoneal dialysis catheter, sequela', 1376);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1377, 'Percutan vertebroplasty', 'Burn of unspecified degree of right wrist, subs encntr', 1377);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1378, 'Creat peritoneovas shunt', 'Toxic effect of glycols, assault, sequela', 1378);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1379, 'Cerebral thermography', 'Poisoning by unsp topical agent, undetermined, sequela', 1379);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1380, 'Atmos press/compos contr', 'Alcoholic gastritis without bleeding', 1380);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1381, 'Destruc-wrist lesion NEC', 'Contusion of fallopian tube, bilateral, initial encounter', 1381);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1382, 'Delayed tendon suture', 'Unspecified open wound of forearm', 1382);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1383, 'Cholecystostomy NEC', 'Secondary corneal edema, bilateral', 1383);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1384, 'Inject anticoagulant', 'Malignant neoplasm of ovrlp sites of unsp eye and adnexa', 1384);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1385, 'Truncal vagotomy', 'Stress fracture, left fibula, subs for fx w malunion', 1385);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1386, 'Bunionectomy NEC', 'Lacerat msl/fasc/tnd post grp at thi lev, unsp thigh, init', 1386);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1387, 'Replace nephrostomy tube', 'Displ spiral fx shaft of ulna, l arm, 7thF', 1387);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1388, 'Influenza vaccination', 'Poisoning by benzodiazepines, accidental, subs', 1388);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1389, 'Injection into prostate', 'Unsp fracture of oth metacarpal bone, subs for fx w nonunion', 1389);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1390, 'Allo hem stem ct w/o pur', 'Partial traumatic amputation of unspecified ear', 1390);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1391, 'Omt with lo-vel,hi-ampli', 'Oth nondisp fx of upper end of unsp humerus, init for opn fx', 1391);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1392, 'Other perm tracheostomy', 'Unspecified injury of unspecified foot, sequela', 1392);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1393, 'Pros rep ventrc def-clos', 'Diffuse cholesteatosis, left ear', 1393);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1394, 'Replace prolapsed cord', 'Nondisp fx of proximal phalanx of left thumb, init', 1394);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1395, 'Muscle trnsfr/transplant', 'Alcohol induced acute pancreatitis', 1395);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1396, 'Opn abdperneal resc rec', 'Toxic effect of other pesticides, undetermined, subs encntr', 1396);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1397, 'C.A.T. scan of kidney', 'Contusion of finger with damage to nail', 1397);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1398, 'Inject tranquilizer', 'Cerebral infrc due to thombos of left ant cerebral artery', 1398);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1399, 'Rectal massage', 'Other physeal fracture of upper end of right femur, sequela', 1399);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1400, 'Tracheoscopy thru stoma', 'Unsp focal TBI w LOC >24 hr w ret consc lev', 1400);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1401, 'Goniotomy w goniopunctur', 'Nondisp fx of 5th metatarsal bone, r ft, 7thP', 1401);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1402, 'Lap gastric restric proc', 'Disp fx of medial condyle of right humerus, init for opn fx', 1402);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1403, 'Create septal defect', 'Open bite of left breast, sequela', 1403);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1404, 'Ovarian denervation', 'Unspecified retinal detachment with retinal break, bilateral', 1404);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1405, 'Immunotherapy as antineo', 'Neoplasm of uncertain behavior of trachea, bronchus and lung', 1405);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1406, 'Tibia/fibula sequestrec', 'Nondisp transverse fx right acetabulum, init for opn fx', 1406);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1407, '2 int mam-cor art bypass', 'Accidental twist by another person, sequela', 1407);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1408, 'Repair of vessel NEC', 'Legal intervnt involving oth means, law enforc offl injured', 1408);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1409, 'One extraoc mus recess', 'Dislocation of distal interphaln joint of unsp finger, init', 1409);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1410, 'Synovectomy-site NEC', 'Displ spiral fx shaft of r tibia, 7thQ', 1410);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1411, 'Vaginal biopsy', 'Minor laceration of unsp internal jugular vein, subs encntr', 1411);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1412, 'Mri musculoskeletal', 'Unspecified injury of left Achilles tendon', 1412);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1413, 'Penile operation NEC', 'Toxic effect of phosphorus and its compounds, assault, init', 1413);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1414, 'Regional lymph node exc', 'Strain extn/abdr musc/fasc/tend of r thm at forarm lv, subs', 1414);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1415, 'Repair of spleen', 'Oth physeal fx upper end of l femur, subs for fx w malunion', 1415);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1416, 'Sex transformat op NEC', 'Other specified deforming dorsopathies, lumbar region', 1416);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1417, 'Periop aut trans hol bld', 'Coma scale, best motor response, extension, unspecified time', 1417);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1418, 'Contrast phlebogram-leg', 'Open bite of scalp, initial encounter', 1418);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1419, 'Suture kidney laceration', 'Other specified arthritis, left shoulder', 1419);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1420, 'Toxicology-peritoneum', 'Outcome of delivery', 1420);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1421, 'Toe injury operation NOS', 'Dislocation of radiocarpal joint of left wrist, init encntr', 1421);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1422, 'Bact smear-eye', 'Unsp injury of muscle and tendon of front wall of thorax', 1422);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1423, 'Closed thyroid gland bx', 'Disp fx of med malleolus of l tibia, 7thP', 1423);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1424, 'Respiratory measure NEC', 'Oth psychoactive substance abuse w oth disorder', 1424);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1425, 'Rabies vaccination', 'Disp fx of coronoid pro of unsp ulna, 7thE', 1425);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1426, 'Retinal tear xenon coag', 'Hyphema, right eye', 1426);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1427, 'Lysis pharyngeal adhes', 'Displ commnt fx shaft of r fibula, 7thQ', 1427);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1428, 'IVUS peripheral vessels', 'Other rheumatic tricuspid valve diseases', 1428);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1429, 'Cardioplegia', 'Contact w and expsr to oth hazards in the physcl environment', 1429);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1430, 'Ureteroscopy', 'Unsp inj extn musc/fasc/tend and unsp finger at wrs/hnd lv', 1430);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1431, 'Endo imp grft thor aorta', 'Headache', 1431);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1432, 'Ins spinal fusion device', 'Passenger on bus injured in clsn w pedl cyc nontraf, sequela', 1432);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1433, 'Cl fx reduc-metacar/car', 'Torus fracture of lower end of ulna', 1433);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1434, 'Shoulder arthroscopy', 'Nondisp fx of olecran pro w/o intartic extn unsp ulna, 7thR', 1434);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1435, 'Catarac phacoemuls/aspir', 'Primary osteoarthritis, right ankle and foot', 1435);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1436, 'Unilat lung transplant', 'Aggressive periodontitis, localized', 1436);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1437, 'Contrast x-ray of sinus', 'Skeletal fluorosis, left forearm', 1437);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1438, 'Remov art anal sphincter', 'Ganglionic blocking drugs', 1438);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1439, 'Open reduc-humerus fx', 'Other physeal fracture of left metatarsal, init', 1439);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1440, 'Remov intralum mouth FB', 'NIHSS score 41', 1440);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1441, 'Open uterine biopsy', 'Mtrcy driver injured in clsn w statnry object in traf, init', 1441);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1442, 'Repair conjunct lacerat', 'Adverse effect of antithyroid drugs, initial encounter', 1442);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1443, 'Lac canaliculi probe', 'Fracture of one rib, left side, subs for fx w nonunion', 1443);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1444, 'Bone graft-radius/ulna', 'Toxic effect of lacrimogenic gas, assault, subs encntr', 1444);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1445, 'Parasitology-lymph sys', 'Unsp physl fx low end humer, l arm, subs for fx w malunion', 1445);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1446, 'Procedure-one vessel', 'Underdosing of thyroid hormones and substitutes, sequela', 1446);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1447, 'Repair ob lac blad/ureth', 'Abrasion of unspecified forearm, sequela', 1447);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1448, 'Remove eye prosthesis', 'Toxic effect of methanol, assault, subsequent encounter', 1448);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1449, 'Implt cochlear prost NOS', 'Oth osteopor w crnt path fx, r humer, subs for fx w nonunion', 1449);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1450, 'Atmos press/compos contr', 'Lacerat extn musc/fasc/tend unsp finger at forarm lv, init', 1450);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1451, 'Skl xray-shoulder/up arm', 'Malignant neoplasm of posterior wall of hypopharynx', 1451);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1452, 'Trans bal dil pros ureth', 'Malignant neoplasm of other and unsp major salivary glands', 1452);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1453, 'Gum or alveolar incision', 'Unspecified subluxation of left foot, sequela', 1453);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1454, 'Part brch extrac w forcp', 'Frostbite w tissue necrosis of right finger(s), subs encntr', 1454);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1455, 'Periurethral incision', 'Burn of unspecified degree of right lower leg, sequela', 1455);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1456, 'Destruct cornea les NEC', 'Ototoxic hearing loss, unspecified ear', 1456);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1457, 'Rectal packing', 'Burn of first degree of multiple sites of wrist and hand', 1457);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1458, 'Coron vess aneurysm rep', 'Oth fx third metacarpal bone, right hand, init for opn fx', 1458);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1459, 'Esophageal dilation', 'Nondisp fx of prox phalanx of r idx fngr, 7thK', 1459);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1460, 'Exc/dest hrt lesion open', 'Corrosion of first degree of left forearm', 1460);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1461, 'Transureteroureterostomy', 'Retained glass fragments', 1461);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1462, 'Thigh reattachment', 'Pain in arm, unspecified', 1462);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1463, 'Lap remove both ovaries', 'Poisoning by otorhino drugs and preparations, self-harm', 1463);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1464, 'Intrathoracic shunt NEC', 'Oth non-ABO incompat react d/t tranfs of bld/bld prod, subs', 1464);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1465, 'Coronar arteriogr-1 cath', 'Polyglandular dysfunction', 1465);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1466, 'Ureteral anastomosis NEC', 'Other specified injuries of unspecified elbow', 1466);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1467, 'Opn/oth rep aortic valve', 'Nondisp unsp fx unsp lesser toe(s), subs for fx w delay heal', 1467);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1468, 'Revision of tracheostomy', 'Laceration without foreign body of unsp buttock, init encntr', 1468);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1469, 'Percut vertebral augment', 'Oth foreign object in bronchus causing asphyxiation, sequela', 1469);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1470, 'Loc exc les metacar/car', 'Rheumatoid heart disease w rheumatoid arthritis of unsp knee', 1470);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1471, 'Endosc destruc esoph les', 'Crushing injury of right foot, initial encounter', 1471);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1472, 'Percutan vertebroplasty', 'Displaced transverse fx shaft of right femur, sequela', 1472);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1473, 'Closed chest card massag', 'Lacerat abd wall w fb, epigst rgn w/o penet perit cav, init', 1473);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1474, 'Head/neck vessel excis', 'Unsp injury of right shoulder and upper arm, init encntr', 1474);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1475, 'Radial keratotomy', 'Sprain of unspecified acromioclavicular joint, init encntr', 1475);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1476, 'Total hip replacement', 'Polyp of vocal cord and larynx', 1476);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1477, 'Surg tooth extract NEC', 'Other specified obstructed labor', 1477);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1478, 'Sympathetic nerve biopsy', 'Rieger''s anomaly', 1478);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1479, 'Bronchoscopy thru stoma', 'Other injury of unspecified part of colon, subs encntr', 1479);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1480, 'Skull flap formation', 'Disp fx of unsp tibial spin, 7thF', 1480);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1481, 'Contr pulmon arteriogram', 'Periprosthetic osteolysis of other internal prosthetic joint', 1481);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1482, 'Rep anuls fibros NEC/NOS', 'Spontaneous rupture of flexor tendons, multiple sites', 1482);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1483, 'Unilat adrenal explorat', 'Pnctr of abd wall w fb, r upper q w/o penet perit cav, subs', 1483);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1484, 'Percut tunica aspiration', 'Corrosion of second degree of right hand, unsp site, subs', 1484);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1485, 'Suture of laryngeal lac', 'Term delivery with preterm labor, unsp trimester, fetus 5', 1485);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1486, 'Pulsation balloon implan', 'Accident to, on or involving ice yacht', 1486);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1487, 'Sinusotomy NOS', 'Oth comp of spinal and epidural anesthesia during pregnancy', 1487);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1488, 'After-cataract excision', 'Melanoma in situ of scalp and neck', 1488);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1489, 'Rad excis ext ear les', 'Oth intentional self-harm by drown, sequela', 1489);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1490, 'Limited rhinoplasty', 'Unspecified injury of transverse colon', 1490);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1491, 'Hand tenonectomy NEC', 'Superficial foreign body of unspecified back wall of thorax', 1491);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1492, 'Head/neck vessel excis', 'Fall d/t clsn betw inflatbl crft and oth wtrcrft/obj, init', 1492);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1493, 'Arthroplasty metacar w/o', 'Child physical abuse, confirmed, subsequent encounter', 1493);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1494, 'Other suture of tendon', 'Injury of oth nerves at lower leg level, left leg, subs', 1494);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1495, 'Breast xerography', 'Unspecified physeal fracture of unspecified calcaneus', 1495);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1496, 'Infusion 4F-PCC', 'Burn of second degree of right knee, sequela', 1496);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1497, 'Closure of anal fistula', 'Superficial foreign body of unsp upper arm, subs encntr', 1497);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1498, 'Cran nerv root decom NEC', 'External constriction of abdominal wall, initial encounter', 1498);
insert into Medical_Record (recordID, treatment, event_record, dischargeID) values (1499, 'Ureteral catheterization', 'Other waiting period for investigation and treatment', 1499);
