
DROP TABLE Doctor CASCADE CONSTRAINTS;
DROP TABLE Nurse CASCADE CONSTRAINTS;
DROP TABLE Operation CASCADE CONSTRAINTS;
DROP TABLE Operation_room CASCADE CONSTRAINTS;
DROP TABLE Equipment CASCADE CONSTRAINTS;
DROP TABLE Assist_By CASCADE CONSTRAINTS;
DROP TABLE Operate_By CASCADE CONSTRAINTS;

DROP TABLE Attending_doctor CASCADE CONSTRAINTS;
DROP TABLE Insured_Patients CASCADE CONSTRAINTS;
